### PR TITLE
Bug fixes

### LINKED ISSUE #80: Submit IPA - Put land act file # next to Authorizing Agency
Land Act file # should be inline with the Authorizing agency, and should only be visible if the `Front Counter BC` option is selected.

Need to find a way to not hard-code the UUID for the show/hide logic, but can use that as an interim solution.

### LINKED ISSUE #126: Submit New Project - Land Act # only visible if project authorizing agency is FCBC
FAIL: Land Act File Number appears and is available for all Project Authoring Agencies.

### LINKED ISSUE #131: New project workflow complete submission step print action fails (Jira ticket 150)

### LINKED ISSUE #132: Print button navigates to incorrect page - When selecting "Print" button, user navigates to a miscellaneous non-functional page that they cannot navigate out of (Jira ticket 142)

### PR DESCRIPTION
**Pull request by P-Hansen**
Bug fixes from the issues board:

-added validation so end date can't be before start date. closes issue #127
-documents not longer needed to proceed passed step 5. closes issue #135
-moved number field to the same line as project authorizing agency closes #80
-land act number field is only visible if project authorizing agency is FCBC. closes #126 
    -made the land act number field conditionally visible on review page
-made "other project type" field conditionally visible on review page to match behaviour on step 3
-location map added to review page
-printing capability added. closes #132 and closes #131

Should close most if not all issues in #123

### CODE REVIEW

File: bcfms/src/bcfms/ipa/pages/SubmitProject/steps/Step2_Details.vue [hunk 1]
```diff
@@ -33,11 +36,43 @@ const projectDetailsResolver = getFlattenResolver(
...
-    return baseIsValid(
+const isValid = (
+    incomingValue?: AliasedNodeData,
+    incomingAttribute?: string,
+) => {
+    const isBaseValid = baseIsValid(
         projectDetailsForm as Ref<FormInstance>,
         ProjectDetailsSchema.shape['aliased_data'],
     );
+
```
Comment (bferguso) [inline bcfms/src/bcfms/ipa/pages/SubmitProject/steps/Step2_Details.vue]: Can this be done in the zod schema? I'd like to keep all the validation there. I think this could potentially be a generic validation, but it could stay in BCFMS for now.

**Review by bferguso — CHANGES_REQUESTED** [review]
Overall looks good! Haven't tested it locally but I'll pull it into my v8 branch after it gets merged in.

**Review by bferguso — APPROVED** [review]
LGTM. I'll get this in so we're on v8 and then we can deal with any small nits later.
